<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[测试方法已经验证通过test]]>
    </line>
  </reporter-output>
  <suite name="执行指定的" duration-ms="0" started-at="2016-12-16T03:36:00Z" finished-at="2016-12-16T03:36:00Z">
    <groups>
    </groups>
  </suite> <!-- 执行指定的 -->
  <suite name="Suite1" duration-ms="2" started-at="2016-12-16T03:36:00Z" finished-at="2016-12-16T03:36:00Z">
    <groups>
    </groups>
    <test name="test1" duration-ms="2" started-at="2016-12-16T03:36:00Z" finished-at="2016-12-16T03:36:00Z">
      <class name="testDemo.Script.testDemo">
        <test-method status="PASS" signature="testHello(java.lang.String, java.lang.String)[pri:0, instance:testDemo.Script.testDemo@5ae9a829]" name="testHello" duration-ms="1" started-at="2016-12-16T11:36:00Z" finished-at="2016-12-16T11:36:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[abcdefg]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[higklmn]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[测试方法已经验证通过test]]>
            </line>
          </reporter-output>
        </test-method> <!-- testHello -->
      </class> <!-- testDemo.Script.testDemo -->
    </test> <!-- test1 -->
  </suite> <!-- Suite1 -->
  <suite name="Suite2" duration-ms="36" started-at="2016-12-16T03:35:59Z" finished-at="2016-12-16T03:35:59Z">
    <groups>
    </groups>
    <test name="test1" duration-ms="36" started-at="2016-12-16T03:35:59Z" finished-at="2016-12-16T03:35:59Z">
      <class name="testDemo.Script.testDemo">
        <test-method status="FAIL" signature="testHello(java.lang.String, java.lang.String)[pri:0, instance:testDemo.Script.testDemo@6276ae34]" name="testHello" duration-ms="7" started-at="2016-12-16T11:35:59Z" finished-at="2016-12-16T11:35:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[abcdef]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[higklm]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [abcdefg] but found [abcdef]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [abcdefg] but found [abcdef]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at testDemo.Script.testDemo.testHello(testDemo.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1260)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testHello -->
      </class> <!-- testDemo.Script.testDemo -->
    </test> <!-- test1 -->
  </suite> <!-- Suite2 -->
</testng-results>
